export const SOLIHULL_SCHOOLS = [
  'Alderbrook School',
  'Arden',
  'Balsall Common Primary School',
  'Bentley Heath Church of England Primary School',
  'Berkswell Church of England Voluntary Aided Primary School',
  'Bishop Wilson Church of England Primary School',
  'Blossomfield Infant and Nursery School',
  'Burman Infant School',
  'Castle Bromwich Infant and Nursery School',
  'Castle Bromwich Junior School',
  'Castlewood School',
  "Chelmsley Wood Children's Centre",
  'Cheswick Green Primary School',
  'Coleshill Heath School',
  'Coppice Academy',
  'Cranmore Infant School',
  'Damson Wood Nursery and Infant School',
  'Daylesford Academy',
  'Dickens Heath Community Primary School',
  'Dorridge Primary School',
  'Eversfield Preparatory School',
  'Fordbridge Community Primary School',
  'Forest Oak School',
  'George Fentham Endowed School',
  'Grace Academy Solihull',
  'Greswold Primary School',
  'Haslucks Green School',
  'Hazel Oak School',
  'Heart of England School',
  'John Henry Newman Catholic College',
  "Keystone Children's Centre (Bentley Heath)",
  'Kineton Green Primary School',
  "Kingshurst Children's Centre",
  'Kingshurst Primary School',
  'Kingswood School',
  'Knowle Church of England Primary Academy',
  'Lady Katherine Leveson Church of England Primary School',
  'Langley School',
  'Light Hall School',
  'Lode Heath School',
  'Lyndon School',
  'Marston Green Infant Academy',
  'Marston Green Junior School',
  'Meriden Church of England Primary School',
  'Merstone School',
  "Mill Lodge Children's Centre (Shirley West)",
  'Mill Lodge Primary School',
  'Monkspath Junior and Infant School',
  'Oak Cottage Primary School',
  'Olton Primary School',
  'Our Lady of Compassion Catholic Primary School',
  'Our Lady of the Wayside Catholic Primary School',
  'Park Hall Academy',
  'Peterbrook Primary School',
  'Reynalds Cross School',
  'Ruckleigh School',
  "Rural Children's Centre",
  'Sharmans Cross Junior School',
  "Shirley Heath Children's Centre (Shirley South)",
  'Shirley Heath Junior School',
  "Smith's Wood Academy",
  "Smith's Wood Children's Centre",
  "Smith's Wood Primary Academy",
  'Solihull Alternative Provision Academy',
  'Solihull College & University Centre',
  'Solihull School',
  'Solihull Sixth Form College',
  'St Alphege Church of England Infant and Nursery School',
  'St Alphege Church of England Junior School',
  "St Andrew's Catholic Primary School",
  "St Anne's Catholic Primary School",
  "St Anthony's Catholic Primary School",
  "St Augustine's Catholic Primary School",
  'St George and St Teresa Catholic Primary School',
  'St John the Baptist Catholic Primary School',
  "St Margaret's Church of England Primary School",
  "St Mary and St Margaret's Church of England Aided Primary School",
  'St Patricks Church of England Primary Academy',
  "St Peter's Catholic School",
  'Streetsbrook Infant and Early Years Academy',
  'The Heights Academy',
  'The Island Project School',
  'Tidbury Green School',
  'Trident Alternative Provision Ltd',
  'Triple Crown Centre',
  'Tudor Grange Academy Kingshurst',
  'Tudor Grange Academy Solihull',
  'Tudor Grange Primary Academy Hockley Heath',
  'Tudor Grange Primary Academy Langley',
  'Tudor Grange Primary Academy St James',
  'Tudor Grange Primary Academy Yew Tree',
  'Ulverley School',
  'Valley Primary',
  'Widney Junior School',
  'Windy Arbor Primary School',
  'WMG Academy for Young Engineers (Solihull)',
  'Woodlands Infant School',
  "Yorkswood Children's Centre",
  'Yorkswood Primary School',
  'Other (Outside of Solihull)',
] as const;

export const SCHOOL_YEARS = [
  'Reception',
  'Year 1',
  'Year 2',
  'Year 3',
  'Year 4',
  'Year 5',
  'Year 6',
  'Year 7',
  'Year 8',
  'Year 9',
  'Year 10',
  'Year 11',
] as const;

export function getPrimaryOrSecondary(schoolYear: string): 'Primary' | 'Secondary' {
  const secondaryYears = ['Year 7', 'Year 8', 'Year 9', 'Year 10', 'Year 11'];
  return secondaryYears.includes(schoolYear) ? 'Secondary' : 'Primary';
}
