export const SOLIHULL_SCHOOLS = [
  'Alderbrook School',
  'Arden',
  'Balsall Common Primary School',
  'Bentley Heath Church of England Primary School',
  'Berkswell Church of England Voluntary Aided Primary School',
  'Bishop Wilson Church of England Primary School',
  'Blossomfield Infant and Nursery School',
  'Burman Infant School',
  'Castle Bromwich Infant and Nursery School',
  'Castle Bromwich Junior School',
  'Castlewood School',
  "Chelmsley Wood Children's Centre",
  'Cheswick Green Primary School',
  'Coleshill Heath School',
  'Coppice Academy',
  'Cranmore Infant School',
  'Damson Wood Nursery and Infant School',
  'Daylesford Academy',
  'Dickens Heath Community Primary School',
  'Dorridge Primary School',
  'Eversfield Preparatory School',
  'Fordbridge Community Primary School',
  'Forest Oak School',
  'George Fentham Endowed School',
  'Grace Academy Solihull',
  'Greswold Primary School',
  'Haslucks Green School',
  'Hazel Oak School',
  'Heart of England School',
  'John Henry Newman Catholic College',
  "Keystone Children's Centre (Bentley Heath)",
  'Kineton Green Primary School',
  "Kingshurst Children's Centre",
  'Kingshurst Primary School',
  'Kingswood School',
  'Knowle Church of England Primary Academy',
  'Lady Katherine Leveson Church of England Primary School',
  'Langley School',
  'Light Hall School',
  'Lode Heath School',
  'Lyndon School',
  'Marston Green Infant Academy',
  'Marston Green Junior School',
  'Meriden Church of England Primary School',
  'Merstone School',
  "Mill Lodge Children's Centre (Shirley West)",
  'Mill Lodge Primary School',
  'Monkspath Junior and Infant School',
  'Oak Cottage Primary School',
  'Olton Primary School',
  'Our Lady of Compassion Catholic Primary School',
  'Our Lady of the Wayside Catholic Primary School',
  'Park Hall Academy',
  'Peterbrook Primary School',
  'Reynalds Cross School',
  'Ruckleigh School',
  "Rural Children's Centre",
  'Sharmans Cross Junior School',
  "Shirley Heath Children's Centre (Shirley South)",
  'Shirley Heath Junior School',
  "Smith's Wood Academy",
  "Smith's Wood Children's Centre",
  "Smith's Wood Primary Academy",
  'Solihull Alternative Provision Academy',
  'Solihull College & University Centre',
  'Solihull School',
  'Solihull Sixth Form College',
  'St Alphege Church of England Infant and Nursery School',
  'St Alphege Church of England Junior School',
  "St Andrew's Catholic Primary School",
  "St Anne's Catholic Primary School",
  "St Anthony's Catholic Primary School",
  "St Augustine's Catholic Primary School",
  'St George and St Teresa Catholic Primary School',
  'St John the Baptist Catholic Primary School',
  "St Margaret's Church of England Primary School",
  "St Mary and St Margaret's Church of England Aided Primary School",
  'St Patricks Church of England Primary Academy',
  "St Peter's Catholic School",
  'Streetsbrook Infant and Early Years Academy',
  'The Heights Academy',
  'The Island Project School',
  'Tidbury Green School',
  'Trident Alternative Provision Ltd',
  'Triple Crown Centre',
  'Tudor Grange Academy Kingshurst',
  'Tudor Grange Academy Solihull',
  'Tudor Grange Primary Academy Hockley Heath',
  'Tudor Grange Primary Academy Langley',
  'Tudor Grange Primary Academy St James',
  'Tudor Grange Primary Academy Yew Tree',
  'Ulverley School',
  'Valley Primary',
  'Widney Junior School',
  'Windy Arbor Primary School',
  'WMG Academy for Young Engineers (Solihull)',
  'Woodlands Infant School',
  "Yorkswood Children's Centre",
  'Yorkswood Primary School',
  'My child\'s school is not listed',
] as const;

export const BIRMINGHAM_SCHOOLS = [
  'Abbey RC Primary School',
  'Acocks Green Primary School',
  'Adderley Primary School',
  'Al-Furqan Primary School',
  'Albert Bradbeer Primary Academy',
  'Allens Croft Primary School',
  'Alston Primary School',
  'Anderton Park Primary School',
  'Anglesey Primary School',
  'Archbishop Ilsley RC School',
  'Arden Primary School',
  'Arena Academy',
  'Ark Boulton Academy',
  'Ark Kings Academy',
  "Ark St Alban's Academy",
  'Ark Tindal Primary Academy',
  'Ark Victoria Academy',
  'Aston Manor Academy',
  'Aston Tower Community Primary School',
  'Aston University Engineering Academy',
  'Audley Primary School',
  'Barford Primary School',
  'Barr View Primary Academy',
  'Bartley Green School',
  'Baskerville School',
  'Beaufort School',
  'Beeches Infant School',
  'Beeches Junior School',
  'Bellfield Infant School',
  'Bellfield Junior School',
  'Bells Farm Primary School',
  'Benson Community School',
  'Billesley Primary School',
  'Birchfield Primary School',
  'Birches Green Primary School',
  'Birmingham Ormiston Academy',
  'Bishop Challoner RC College',
  "Bishop Vesey's Grammar School",
  'Bishop Walsh RC School',
  'Blakesley Hall Primary School',
  'BOA Digital Technologies Academy',
  'Boldmere Infant School',
  'Boldmere Junior School',
  "Bordesley Green Girls' School",
  'Bordesley Green Primary School',
  'Bordesley Village Primary School',
  'Bournville School',
  'Bournville Village Primary',
  'Braidwood School for The Deaf',
  'Brays School',
  'Broadmeadow Infant School',
  'Broadmeadow Junior School',
  'Broadway Academy',
  'Brookfields Primary School',
  'Brookvale Primary School',
  'Brownmead Primary Academy',
  'Calthorpe Academy',
  'Calshot Primary School',
  'Canterbury Cross Primary School',
  'Cardinal Wiseman RC School',
  'Cedars Academy',
  'Chad Vale Primary School',
  'Chandos Primary School',
  'Cherry Oak School',
  'Cherry Orchard Primary School',
  'Chilcote Primary School',
  'Chilwell Croft Academy',
  'Chivenor Primary School',
  'Christ Church - Church Of England Secondary Academy',
  'Christ Church CE Primary School',
  'Christ the King RC Primary School',
  'City Academy',
  'City of Birmingham School',
  'City Road Primary School',
  'Clifton Primary School',
  'Cockshut Hill School',
  'Cofton Primary School',
  'Colebourne Primary School',
  'Colmers Farm Primary School',
  'Colmers School',
  'Colmore Infant School',
  'Colmore Junior School',
  'Conway Primary School',
  'Coppice Primary School',
  'Corpus Christi RC Primary School',
  'Cottesbrooke Infant School',
  'Cotteridge Primary School',
  'Court Farm Primary School',
  'Cromwell Junior & Infant School',
  'Dame Elizabeth Cadbury School',
  'Deykin Avenue Junior & Infant School',
  'Dorrington Academy',
  'East Birmingham Network Academy',
  'EBN Academy',
  "Eden Boys' Leadership Academy",
  "Eden Boys' School",
  "Eden Girls' Leadership Academy",
  'Elms Farm Community Primary School',
  "English Martyrs' RC Primary School",
  'Erdington Academy',
  'Erdington Hall Primary School',
  'Fairfax Academy',
  'Fairway Primary Academy',
  'Featherstone Primary School',
  'Firs Primary School',
  'Forestdale Primary School',
  'Fortis Academy',
  'Four Dwellings Academy',
  'Four Dwellings Primary Academy',
  'Four Oaks Primary School',
  'Fox Hollies School',
  'George Dixon Academy',
  'George Dixon Primary School',
  'Gilbertstone Primary School',
  'Glenmead Primary School',
  'Gossey Lane Academy',
  'Great Barr Primary School',
  'Green Meadow Primary School',
  'Greenholm Primary School',
  'Greenwood Academy',
  'Greet Primary School',
  'Grendon Primary School',
  'Grestone Academy',
  'Grove School',
  'Guardian Angels RC Primary School',
  'Gunter Primary School',
  'Hall Green Infant School',
  'Hall Green Junior School',
  'Hall Green School',
  'Hallmoor School',
  'Hamilton School',
  'Hamstead Hall Academy',
  'Harborne Academy',
  'Harborne Primary School',
  'Harper Bell Seventh-day Adventist School',
  'Hawkesley Church Primary Academy',
  'Hawthorn Primary School',
  'Heath Mount Primary School',
  'Heathfield Primary School',
  'Heathlands Primary Academy',
  'Heartlands Academy',
  'Highfield Junior & Infant School',
  'Highters Heath Community School',
  'Hill West Primary School',
  'Hillcrest School',
  'Hillstone Primary School',
  'Hodge Hill College',
  "Hodge Hill Girls' School",
  'Hodge Hill Primary School',
  'Holland House Infant School',
  'Holly Hill Methodist/CE Infant School',
  'Hollyfield Primary School',
  'Hollywood Primary School',
  'Holy Cross RC Primary School',
  'Holy Family RC Primary School',
  'Holy Souls RC Primary School',
  'Holy Trinity CE Primary Academy',
  'Holy Trinity RC School',
  'Holte School',
  'Holyhead School',
  'James Brindley School',
  'James Watt Primary School',
  'Jervoise School',
  'Jewellery Quarter Academy',
  'John Willmott School',
  'King David Primary School',
  'King Edward VI Aston School',
  'King Edward VI Balaam Wood Academy',
  'King Edward VI Camp Hill School for Boys',
  'King Edward VI Camp Hill School for Girls',
  'King Edward VI Five Ways School',
  'King Edward VI Handsworth Grammar School for Boys',
  'King Edward VI Handsworth School',
  "King Edward VI Handsworth Wood Girls' Academy",
  'King Edward VI Northfield School for Girls',
  'King Edward VI Sheldon Heath Academy',
  'King Solomon International Business School',
  "King's Norton Boys' School",
  'Kings Heath Boys',
  'Kings Heath Primary School',
  "Kings Norton Girls' School",
  'Kings Norton Junior & Infant School',
  'Kings Rise Academy',
  'Kingsland Primary School',
  'Kingsthorne Primary School',
  'Kitwell Primary School',
  'Ladypool Primary School',
  'Lakey Lane Junior & Infant School',
  'Langley School',
  'Lea Forest Primary Academy',
  'Lea Hall Academy',
  'Leigh Primary School',
  'Leycroft Academy',
  'Lindsworth School',
  'Little Sutton Primary School',
  'Longwill School for the Deaf',
  "Lordswood Boys' School",
  "Lordswood Girls' School",
  'Lozells Junior & Infant School',
  'Lyndon Green Infant School',
  'Lyndon Green Junior School',
  'Maney Hill Primary School',
  'Manor Park Primary Academy',
  'Mansfield Green E-ACT Academy',
  'Mapledene Primary School',
  'Marlborough Primary School',
  'Marsh Hill Primary School',
  'Maryvale RC Primary School',
  'Mayfield School',
  'Mere Green Primary School',
  'Merritts Brook Primary E-ACT Academy',
  'Minworth Junior & Infant School',
  'Montgomery Primary Academy',
  'Moor Green Primary School',
  'Moor Hall Primary School',
  'Moseley CE Primary School',
  'Moseley School',
  'Nansen Primary School',
  'Nechells Primary E-ACT Academy',
  'Nelson Junior & Infant School',
  'Nelson Mandela School',
  'New Hall Primary School',
  'New Oscott Primary School',
  'Ninestiles Academy',
  'Nishkam High School',
  'Nishkam Primary School',
  'Nonsuch Primary School',
  'North Birmingham Academy',
  'Northfield Manor Primary Academy',
  'Oasis Academy Blakenhale Infants',
  'Oasis Academy Blakenhale Junior',
  'Oasis Academy Boulton',
  'Oasis Academy Foundry',
  'Oasis Academy Hobmoor',
  'Oasis Academy Short Heath',
  'Oasis Academy Woodview',
  'Oscott Manor School',
  'Osborne Primary School',
  'Our Lady & St Rose of Lima RC Primary School',
  'Our Lady of Fatima RC Primary School',
  'Our Lady of Lourdes RC Primary School',
  "Our Lady's RC Primary School",
  'Paganel Primary School',
  'Paget Primary School',
  'Park Hill Primary School',
  'Parkfield Community School',
  'Pegasus Primary Academy',
  'Penns Primary School',
  'Percy Shurmer Academy',
  'Plantsbrook School',
  'Priestley Smith School',
  'Prince Albert High School',
  'Prince Albert Junior & Infant School',
  'Princethorpe Infant School',
  'Princethorpe Junior School',
  'Queensbridge School',
  'Queensbury School',
  'Quinton Church Primary School',
  'Raddlebarn Primary School',
  'Reach School',
  'Reaside Academy',
  'Redhill Primary School',
  'Rednal Hill Infant School',
  'Rednal Hill Junior School',
  'Regents Park Community Primary School',
  'Robin Hood Academy',
  'Rockwood Academy',
  'Rookery School',
  'Sacred Heart RC Primary School',
  'Saltley Academy',
  'Selly Oak Trust School',
  "Selly Park Girls' School",
  'Severne Junior & Infant School',
  'Shaw Hill Primary School',
  'Shenley Academy',
  'Slade Primary School',
  'Sladefield Infant School',
  'Small Heath Leadership Academy',
  'Somerville Primary School',
  'Springfield House Community Special School',
  'Springfield Primary Academy',
  'SS John and Monica RC Primary School',
  "St Alban's RC Primary School",
  'St Ambrose Barlow RC Primary School',
  "St Anne's RC Primary School",
  "St Augustine's RC Primary School",
  'St Barnabas CE Primary School',
  "St Benedict's Primary School",
  "St Bernadette's RC Primary School",
  "St Bernard's RC Primary School",
  "St Brigid's RC Primary School",
  'St Catherine of Siena RC Primary School',
  "St Chad's RC Primary School",
  "St Clare's RC Primary School",
  "St Clement's CE Academy",
  "St Columba's RC Primary School",
  "St Cuthbert's RC Junior & Infant School",
  "St Dunstan's RC Primary School",
  'St Edmund Campion RC School',
  "St Edmund's RC Primary School",
  "St Edward's RC Primary School",
  'St Francis CE Primary School',
  'St Francis RC Primary School',
  "St George's CE Academy",
  "St George's CE Primary School",
  "St Gerard's RC Junior & Infant School",
  'St James CE Primary School',
  'St James RC Primary School',
  'St John Fisher RC Primary School',
  'St John Wall RC School',
  "St John's & St Peter's CE Academy",
  "St John's CE Primary School",
  "St Joseph's RC Primary School",
  "St Jude's RC Primary School",
  'St Laurence Church Infant School',
  'St Laurence Church Junior School',
  'St Margaret Mary RC Junior & Infant School',
  "St Mark's RC Primary School",
  'St Martin de Porres RC Primary School',
  'St Mary & St John Junior & Infant School',
  "St Mary's CE Primary Academy",
  "St Mary's CE Primary School",
  "St Mary's RC Primary School",
  "St Matthew's CE Primary School",
  "St Michael's CE Primary Academy",
  "St Michael's CE Primary School",
  'St Nicholas RC Primary School',
  "St Patrick's RC Primary School",
  "St Paul's RC Primary School",
  "St Paul's School for Girls",
  'St Peter & St Paul RC Junior & Infant School',
  "St Peter's CE Primary School",
  "St Peter's RC Primary School",
  "St Saviour's CE Primary School",
  "St Teresa's RC Primary School",
  'St Thomas Aquinas RC School',
  'St Thomas CE Academy',
  'St Thomas More RC Primary School',
  "St Vincent's RC Primary School",
  "St Wilfrid's RC Junior & Infant School",
  'Stanville Primary School',
  'Starbank School',
  'Stechford Primary School',
  'Stirchley Primary School',
  'Stockland Green School',
  'Story Wood School',
  'Summerfield Junior & Infant School',
  'Sundridge Primary School',
  'Sutton Coldfield Grammar School for Girls',
  'Sutton Park Primary',
  'Swanshurst School',
  'Tame Valley Academy',
  'The Arthur Terry School',
  'The Bridge School',
  'The Dame Ellen Pinsent School',
  'The Deanery CE Primary School',
  'The Edge Academy',
  'The Meadows Primary School',
  'The Oaklands Primary School',
  'The Oaks Primary School',
  'The Olive School Birmingham',
  'The Olive School Small Heath',
  'The Orchards Primary Academy',
  'The Oratory RC Primary School',
  'The Oval School',
  'The Pines Special School',
  'The Rosary RC Primary School',
  'The Shirestone Academy',
  'Thornton Primary School',
  'Tile Cross Academy',
  'Timberley Academy',
  'Titan Aston Academy',
  "Titan St George's Academy",
  'Tiverton Academy',
  'Topcliffe Primary School',
  'Town Junior School',
  "Turves Green Boys' School",
  'Turves Green Primary School',
  'Twickenham Primary School',
  'Uffculme School',
  'University of Birmingham School',
  'Victoria School',
  'Walmley Infant School',
  'Walmley Junior School',
  'Ward End Primary School',
  'Warren Farm Primary School',
  'Washwood Heath Academy',
  'Water Mill Primary School',
  'Wattville Primary School',
  'Waverley School',
  'Waverley Studio College',
  'Welford Primary School',
  'Welsh House Farm Community School',
  'West Heath Primary School',
  'Westminster Primary School',
  'Wheelers Lane Primary School',
  'Wheelers Lane Technology College',
  'Whitehouse Common Primary School',
  'William Murdoch Primary School',
  'Wilson Stuart School',
  'Windsor Olympus Academy',
  'Woodcock Hill Primary School',
  'Woodgate Primary School',
  'Woodhouse Primary Academy',
  'Woodthorpe Junior & Infant School',
  "World's End Infant School",
  "World's End Junior School",
  'Wychall Primary School',
  'Wylde Green Primary School',
  'Wyndcliffe Primary School',
  'Yardley Primary School',
  'Yardley Wood Community Primary School',
  'Yardleys School',
  'Yarnfield Primary School',
  'Yenton Primary School',
  'Yew Tree Community Junior & Infant School',
  'Yorkmead Junior & Infant School',
  'My child\'s school is not listed',
] as const;

export const SCHOOL_YEARS = [
  'Reception',
  'Year 1',
  'Year 2',
  'Year 3',
  'Year 4',
  'Year 5',
  'Year 6',
  'Year 7',
  'Year 8',
  'Year 9',
  'Year 10',
  'Year 11',
] as const;

export function getPrimaryOrSecondary(schoolYear: string): 'Primary' | 'Secondary' {
  const secondaryYears = ['Year 7', 'Year 8', 'Year 9', 'Year 10', 'Year 11'];
  return secondaryYears.includes(schoolYear) ? 'Secondary' : 'Primary';
}

export function getSchoolsForRegion(region: string): readonly string[] {
  if (region === 'birmingham') return BIRMINGHAM_SCHOOLS;
  return SOLIHULL_SCHOOLS;
}
